function createCsvFiles()

subFolder0 = ["0.1_simulation_configurations", ...
    "0.2_numerical_methods", ...
    "0.3_simulation_outputs", ...
    "1.1_natural_constants", ...
    "1.2_adsorbate_properties", ...
    "1.3_adsorbent_properties", ...
    "2.1_feed_stream_properties", ...
    "2.2_raffinate_stream_properties", ...
    "2.3_extract_stream_properties", ...
    "3.1_adsorber_properties", ...
    "3.2_feed_tank_properties", ...
    "3.3_raffinate_tank_properties", ...
    "3.4_extract_tank_properties", ...
    "3.5_feed_compressor_properties", ...
    "3.6_extract_compressor_properties", ...
    "3.7_vacuum_pump_properties", ...
    "4.1_cycle_organization"];

numExFilesFolder = length(subFolder0);

for j = 1 : numExFilesFolder
    exFileName = subFolder0(j);
    writetable(readtable(exFileName + ".xlsm","Sheet","Data(Transposed)"),exFileName + ".csv");
    writetable(readtable(exFileName + ".xlsm","Sheet","Data(Test)"),exFileName + ".csv",WriteMode="append");    
end

end